apiVersion: v1
kind: Template
metadata:
  name: papermill-buildconfig
  annotations:
    description: "BuildConfig for analysis with parameterized jupyter notebook."
    openshift.io/display-name: "Thoth: Papermill BuildConfig"
    version: 0.1.0
    tags: thoth,ai-stacks,aistacks
    template.openshift.io/documentation-url: https://github.com/AICoE/Thoth/
    template.openshift.io/long-description: "This template defines resources
    needed for the jupyter notebook parameterization using papermill."
    template.openshift.io/provider-display-name: Red Hat, Inc.
    thoth-station.ninja/template-version: 0.1.0
  labels:
    template: papermill-buildconfig
    app: thoth
    component: papermill

parameters:
  - description: "Git repository for papermill work flow"
    displayName: "Thoth: Papermill BuildConfig"
    required: true
    name: GITHUB_URL
    value: "git@github.com:shruthi-raghuraman/jupyter-notebook-openshift.git"

  - description: Git repository for Thoth's User API
    displayName: Thoth user-api git reference
    required: true
    name: GITHUB_REF
    value: "master"

  - description: Tag of the output ImageStream the resulting container image should go to
    displayName: ImageStream Tag
    required: true
    name: IMAGE_STREAM_TAG
    value: "latest"

objects:
  - apiVersion: build.openshift.io/v1
    kind: BuildConfig
    metadata:
      annotations:
        thoth-station.ninja/template-version: 0.9.0
      labels:
        app: thoth
        component: papermill
      name: papermill-job
    spec:
      resources:
        limits:
          cpu: 1
          memory: 1Gi
        requests:
          cpu: 1
          memory: 512Mi
      output:
        to:
          kind: ImageStreamTag
          name: "papermill-job:${IMAGE_STREAM_TAG}"
      runPolicy: Serial
      source:
        sourceSecret:
          name: shruthisecret
        git:
          uri: "${GITHUB_URL}"
          ref: "${GITHUB_REF}"
        type: Git
      strategy:
        dockerStrategy:
          dockerfilePath: Dockerfile
          noCache: true
        env:
          - name: ENABLE_PIPENV
            value: "1"
          - name: UPGRADE_PIP_TO_LATEST
            value: ""
        type: Docker
      triggers:
        - imageChange: {}
          type: ImageChange
