---
apiVersion: v1
kind: Template
metadata:
  annotations:
    description: "BuildConfig for analysis with parameterized jupyter notebook."
    openshift.io/display-name: "Papermill CronJob"
    tags: "thoth,ai-stacks"
    template.openshift.io/documentation-url: https://github.com/AICoE/Thoth/
    template.openshift.io/long-description: "This is containerized jupyter notebooks with Papermill"
    template.openshift.io/provider-display-name: "Red Hat, Inc."
    version: "0.1.0"
  labels:
    app: thoth
    component: papermill
    template: papermill-cronjob
  name: papermill-cronjob

objects:
  - apiVersion: batch/v1beta1
    kind: CronJob
    metadata:
      labels:
        app: thoth
        component: papermill
      name: papermill
    spec:
      concurrencyPolicy: Forbid
      failedJobsHistoryLimit: 1
      jobTemplate:
        spec:
          template:
            metadata:
              labels:
                app: thoth
                component: papermill
            spec:
              containers:
                - image: papermill-job
                  name: papermill
                  resources:
                    limits:
                      cpu: 500m
                      memory: 1Gi
                    requests:
                      cpu: 500m
                      memory: 1Gi
                  env:
                    - name: PIPENV_NOSPIN
                      value: "1"
                    - name: PIPENV_COLORBLIND
                      value: "1"
                    - name: PIPENV_COLORBLIND
                      value: "1"
                    - name: PIPENV_HIDE_EMOJIS
                      value: "1"

                    # - name: GITHUB_TOKEN
                    #   valueFrom:
                    #     secretKeyRef:
                    #       key: github-oauth-token
                    #       name: papermill-secret

                    - name: GITHUB_USER_NAME
                      valueFrom:
                        secretKeyRef:
                          key: user-name
                          name: papermill-secret
                    - name: GITHUB_USER_EMAIL
                      valueFrom:
                        secretKeyRef:
                          key: user-email
                          name: papermill-secret
                    - name: AWS_ACCESS_KEY_ID
                      valueFrom:
                        secretKeyRef:
                          key: aws_key
                          name: papermill-secret
                    - name: AWS_SECRET_ACCESS_KEY
                      valueFrom:
                        secretKeyRef:
                          key: aws_secret
                          name: papermill-secret
                    - name: REPORTER_SSH_PRIVATE_KEY
                      valueFrom:
                        secretKeyRef:
                          key: ssh-privatekey
                          name: jupyter-notebook-openshift

              restartPolicy: Never
      schedule: "@daily"
      successfulJobsHistoryLimit: 2
      suspend: false
