apiVersion: v1
kind: Template
metadata:
  name: papermill-imagestream
  annotations:
    description: "This is the papermill ImageStream"
    openshift.io/display-name: "Papermill ImageStream"
    version: 0.1.0
    tags: thoth,ai-stacks,aistacks
    template.openshift.io/documentation-url: https://github.com/AICoE/Thoth/
    template.openshift.io/long-description: This is the papermill ImageStream
    template.openshift.io/provider-display-name: "Red Hat, Inc."
    thoth-station.ninja/template-version: 0.1.0
  labels:
    template: papermill-imagestream
    app: thoth
    component: papermill

objects:
  - apiVersion: image.openshift.io/v1
    kind: ImageStream
    metadata:
      annotations:
        thoth-station.ninja/template-version: 0.1.0
      labels:
        app: thoth
        component: papermill
      name: papermill-job
    spec:
      name: latest
      lookupPolicy:
        local: true
