---
apiVersion: v1
kind: Template
metadata:
  annotations:
    description: "This is Papermill Secret Config"
    openshift.io/display-name: "Papermill Secret"
    tags: "thoth,ai-stacks"
    template.openshift.io/documentation-url: https://github.com/AICoE/Thoth/
    template.openshift.io/long-description: "This is containerized papermill notebook."
    template.openshift.io/provider-display-name: "Red Hat, Inc."
    version: "0.1.0"
  labels:
    app: thoth
    component: papermill
    template: papermill-secret
  name: papermill-secret

objects:
  - apiVersion: v1
    kind: Secret
    metadata:
      labels:
        app: thoth
        component: papermill
      name: papermill-secret
    type: kubernetes.io/ssh-auth
    stringData:
      ssh-privatekey: "${REPORTER_SSH_PRIVATE_KEY}"
      user-name: "${GITHUB_USER_NAME}"
      user-email: "${GITHUB_USER_EMAIL}"
      aws_key: "${AWS_KEY}"
      aws_secret: "${AWS_SECRET_KEY}"

parameters:
  - description: "SSH private key to authenticate public key."
    displayName: "SSH Private Key"
    name: REPORTER_SSH_PRIVATE_KEY
    required: true

  - description: "User email to log in to Github."
    displayName: "Github user email"
    name: GITHUB_USER_EMAIL
    required: true

  - description: "User name to log in to Github."
    displayName: "Github user name"
    name: GITHUB_USER_NAME
    required: true

  - description: "Aws key to access s3 data."
    displayName: "Aws key"
    name: AWS_KEY
    required: true

  - description: "Aws secret key to access s3 data."
    displayName: "Aws secret key"
    name: AWS_SECRET_KEY
    required: true
